services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: perritos_db
    ports:
      - "3306:3306"
    volumes:
      - perritos_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: perritos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-usecret", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  perritos_data:
